### ISSUE TITLE
Node red terminal spamming

### ISSUE THREAD

**Issue by 877dev** [gablau/node-red-contrib-blynk-iot#11]
Not sure why but today I noticed this:

![image](https://github.com/gablau/node-red-contrib-blynk-iot/assets/46575282/02a11030-b614-4999-9c69-ae9399d492e4)

[info] [blynk-iot-client:Blynk Node Red] ## TLS state: open

**Comment by gablau** [comment]
I believe you have an old version (0.1.0 or 0.2.0) of the library , please update 1.0.0 version.

**Comment by 877dev** [comment]
I updated and it's fixed, many thanks! 

![image](https://github.com/gablau/node-red-contrib-blynk-iot/assets/46575282/ff224318-4e62-49c2-81a5-d4d9077d27a7)
