### ISSUE TITLE
Palette Manager shows red exclamation mark

### ISSUE THREAD

**Issue by Peterkn2001** [gablau/node-red-contrib-blynk-iot#2]
The Palette Manager shows a red triangle with an exclamation mark, and the message [object Object] when the contrib is installed.

There seems to be a missing entry about half way down the list of nodes, with one "disable" button partly hidden behind another...

![image](https://user-images.githubusercontent.com/35718564/123520487-e6cd5c00-d6a8-11eb-9ad2-0fd7fbe166f1.png)

Pete.

**Comment by gablau** [comment]
Old *email* node not deleted in package.json. 
Fixed in the next release

**Comment by Peterkn2001** [comment]
Fixed in v0.2.0

Many thanks,

Pete.
