### ISSUE TITLE
Missing Node - Sync

### ISSUE THREAD

**Issue by Peterkn2001** [gablau/node-red-contrib-blynk-iot#4]
I've noticed that the Sync node is missing.

Blynk are changing the way that `Blynk.syncAll()` works in C++, and at the moment is doesn't work at all.
See this for more info...

https://github.com/blynkkk/blynk_Issues/issues/139

However, `Blynk,syncVirtual(vPin)` does still work, and the ability to send a sync request on a single virtual pin would be extremely useful in Node-Red.
Is it possible to add this back-in, without the "All" option (at least for now)?

Pete.

**Comment by gablau** [comment]
Yeah good! Fix in next release.
- Recover accidentally deleted node Sync in package.json
- allow multiple pins send with "syncVirtual" mode. (separate multiple pins with comma)

**Comment by Peterkn2001** [comment]
Tested and working well in v0.2.0
The syncAll option doesn't work, but as I said earlier that is because of a change that Blynk introduced.
The comma separated list of pins is a nice idea, and works well.

Many thanks!

Pete.

**Comment by Peterkn2001** [comment]
**UPDATE**

Blynk have now released the "Sync with latest server value every time device connects to the cloud" option when defining datasteams (which as to be done in the web portal)
Despite the strange name, this seems to mean "allow Blynk.syncAll to return the value of this pin"

![image](https://user-images.githubusercontent.com/35718564/123554426-d506ba00-d777-11eb-9659-b6be249f6738.png)

With this option enabled, the syncAll option in Sync node does work for the datastreams that have this enabled, so the syncAll option should be retained.

One thing I noticed is that if you set the Sync node to one of the virtual pins, or a comma separated list of pins, then this remains in the node display when you then switch to syncAll...

![image](https://user-images.githubusercontent.com/35718564/123554601-ae954e80-d778-11eb-8317-e3040c64319f.png)

Pete.

**Comment by gablau** [comment]
Fix on [1.0.0](https://github.com/gablau/node-red-contrib-blynk-iot/releases/tag/1.0.0) release
