### ISSUE TITLE
notify

### ISSUE THREAD

**Issue by dansass** [gablau/node-red-contrib-blynk-iot#9]
Just wondering when the blynk notify will be coming or is is not on the road map?

**Comment by gablau** [comment]
Hello, 
unlike the previous platform, notifications are sent by the server here, there is no way to send them directly from the devices.

As you see [here](https://docs.blynk.io/en/getting-started/notification-management), to send a notification you have to use events and automations, you can use the "Log Event" node to send an event and then you have to connect an automation to this event to fire a notification, it's all more complicated than the legacy blynk.

Regards
